/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import javax.swing.JOptionPane;

/**
 *
 * @author Bijon
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundPannel = new javax.swing.JPanel();
        loadinglabel = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        Doctors = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loadingvalue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BackGroundInage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackGroundPannel.setBackground(new java.awt.Color(0, 204, 204));
        BackGroundPannel.setPreferredSize(new java.awt.Dimension(900, 500));
        BackGroundPannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadinglabel.setBackground(new java.awt.Color(255, 255, 255));
        loadinglabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadinglabel.setForeground(new java.awt.Color(255, 255, 255));
        loadinglabel.setText("Loading...");
        BackGroundPannel.add(loadinglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        LoadingBar.setBackground(new java.awt.Color(255, 255, 255));
        BackGroundPannel.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 490, 910, -1));

        Doctors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Assets/t5vasool-removebg-preview.png"))); // NOI18N
        BackGroundPannel.add(Doctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 430, 250));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MEDI CARE PLUS +");
        BackGroundPannel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Patient Dead");
        BackGroundPannel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 51));
        jLabel4.setText("Operation success");
        BackGroundPannel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        loadingvalue.setBackground(new java.awt.Color(255, 255, 255));
        loadingvalue.setForeground(new java.awt.Color(255, 255, 255));
        loadingvalue.setText("0   %");
        BackGroundPannel.add(loadingvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 30, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TEAM BIJON PROUDLY PRESENTS");
        BackGroundPannel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        BackGroundInage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Assets/out.jpeg"))); // NOI18N
        BackGroundInage.setPreferredSize(new java.awt.Dimension(400, 200));
        BackGroundPannel.add(BackGroundInage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGroundPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGroundPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      SplashScreen sp = new SplashScreen();
      sp.setVisible(true);
      
      try
      {
          for(int i=0; i<=100;i++)
          {
              Thread.sleep(100);
              sp.loadingvalue.setText(i + "%");
              
              if(i==10)
              {
                  sp.loadinglabel.setText("Turning On modules...");
              }
              if(i==20)
              {
                  sp.loadinglabel.setText("Loading Modules...");
                  
              }
              if(i==50)
              {
                  sp.loadinglabel.setText("Connecting to Database...");
                  
              }
              if(i==70)
              {
                  sp.loadinglabel.setText("Connection  Successful !");
                  
              }
              if(i==80)
              {
                  sp.loadinglabel.setText("Launching Application...");
                  
              }
              sp.LoadingBar.setValue(i);
          }
          
          sp.dispose();
            new login().setVisible(true);
      }
      
      catch (Exception e)
      {
          JOptionPane.showMessageDialog(null, e);
      }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundInage;
    private javax.swing.JPanel BackGroundPannel;
    private javax.swing.JLabel Doctors;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel loadinglabel;
    private javax.swing.JLabel loadingvalue;
    // End of variables declaration//GEN-END:variables
}
